spring.application.name=charity_hub
spring.data.mongodb.host=localhost
spring.data.mongodb.database=charity_db
spring.data.mongodb.username=admin
spring.data.mongodb.password=charity_password
spring.data.mongodb.port=27017
server.port=8080
cases-service.url=http://localhost:8081

# Feign client configuration
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000
feign.client.config.default.loggerLevel=full
logging.level.com.charity_hub.cases.shared.CasesClient=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.feign=DEBUG
logging.level.org.springframework.web=DEBUG

#management.datadog.metrics.export.apiKey
#logging.level.org.springframework.security=TRACE

auth.secretKey=58fb365a7d09b11ac793400a2a85ecddc966099576c4d10510abce378ad216ca56232c9110b9a8c54aedfa80660a8653cc29460f04b3301171123b1e5cca8d031dea452d932fefb9f8092d4342ccb9514693581cf4708437620a53c65cf7a076bc820588aff4aa3b01876a8dcb04005152c5978afe9882b7bbaaa2b006a960e7c5ad89ba36f838c3cd1c8e3a841468e7ed8bd1a5adf276f974f52cabcdf6d8e7e84d266282b1b7464703064a2853f5982a46239066e4002c017635b8eedcf0c55a0759734891f07b706c6620c79cec329603bd9ebb92d34eb7c2f797da54f1a81402fa0fb246fd54406a9368505d952b5c0162bdaf7e65fe3cfcf0a723a955df
accounts.admins=201260032636,201260032632,201260032631
firebase.service-account-path=./cert/adminsdk.json
firebase.test-mode=true
logging.structured.format.console=ecs
cases.initial-code=20039


# Logging
logging.level.root=INFO
logging.file.path=/var/log/charityhub
logging.file.name=/tmp/charityhub/spring-boot.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
#logging.pattern.file=%d{yyyy-MM-dd:ss.SSS} [%thread] %-5level %logger{36} [dd.trace_id=%X{dd.trace_id} dd.span_id=%X{dd.span_id}] - %msg%n
logging.pattern.file={"timestamp":"%d{yyyy-MM-dd:ss.SSS}","level":"%level","logger":"%logger","trace_id":"%X{dd.trace_id}","span_id":"%X{dd.span_id}","message":"%msg"}%n

# Micrometer & Datadog
management.datadog.metrics.export.apiKey=${DATADOG_API_KEY}
management.datadog.metrics.export.applicationKey=${DATADOG_APPLICATION_KEY}
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.descriptionsEnabled=true
management.datadog.metrics.export.uri=https://api.us5.datadoghq.com
logging.level.io.micrometer.datadog=INFO

#dd.env=local2
#dd.service=${DATADOG_SERVICE}
#dd.version=1.0.0
#dd.logs.injection=true
dd.trace.logs.injection=true
dd.tags=source:java,env:local,service:charityhub-service
